'use client'

import { useState, useMemo, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { zodResolver } from '@hookform/resolvers/zod'
import { useForm } from 'react-hook-form'
import * as z from 'zod'
import { toast } from 'sonner'
import { createClient } from '@/lib/supabase/client'
import { Button } from '@/components/ui/button'
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { PlusCircle, Loader2, Calendar, Info, Bell } from 'lucide-react'
import { addWeeks, format, getDay } from 'date-fns'
import { es } from 'date-fns/locale'
import type { AlertaPlantillaDefecto } from '@/lib/supabase/types'

const DAY_NAMES = ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado']
const NUM_CLASES = 5

function generateClassDates(fechaInicio: string): string[] {
  if (!fechaInicio) return []
  const start = new Date(fechaInicio + 'T12:00:00')
  if (isNaN(start.getTime())) return []
  const dates: string[] = []
  for (let i = 0; i < NUM_CLASES; i++) {
    const d = addWeeks(start, i)
    dates.push(format(d, 'yyyy-MM-dd'))
  }
  return dates
}

function getDayName(fechaInicio: string): string {
  if (!fechaInicio) return ''
  const d = new Date(fechaInicio + 'T12:00:00')
  if (isNaN(d.getTime())) return ''
  return DAY_NAMES[getDay(d)]
}

const formSchema = z.object({
  nombre: z.string().min(2, { message: 'El nombre debe tener al menos 2 caracteres.' }),
  fecha_inicio: z.string().refine((val) => !isNaN(Date.parse(val)), { message: 'Fecha de inicio invalida.' }),
  hora_inicio: z.string().min(1, { message: 'Hora inicio requerida.' }),
  hora_fin: z.string().min(1, { message: 'Hora fin requerida.' }),
  whatsapp_link: z.string().min(10, { message: 'Debe ser un enlace de WhatsApp valido.' }),
})

function resolveAnchorDate(anchor: string, claseDates: string[]): string {
  if (anchor.startsWith('clase_')) {
    const idx = parseInt(anchor.split('_')[1]) - 1
    return claseDates[idx] || claseDates[claseDates.length - 1]
  }
  if (anchor === 'post_ultima_clase') return claseDates[claseDates.length - 1]
  if (anchor === 'fecha_inicio') return claseDates[0]
  if (anchor === 'fecha_fin') return claseDates[claseDates.length - 1]
  return claseDates[0]
}

function computeAlertDate(anchor: string, offsetDias: number, claseDates: string[]): string {
  const base = resolveAnchorDate(anchor, claseDates)
  const date = new Date(base + 'T12:00:00')
  date.setDate(date.getDate() + offsetDias)
  return format(date, 'yyyy-MM-dd')
}

const ANCHOR_LABELS: Record<string, string> = {
  clase_1: 'Clase 1', clase_2: 'Clase 2', clase_3: 'Clase 3',
  clase_4: 'Clase 4', clase_5: 'Clase 5', post_ultima_clase: 'Post ultima clase',
  fecha_inicio: 'Inicio', fecha_fin: 'Fin',
}

export function CreateCourseForm({ onSuccess }: { onSuccess?: () => void }) {
  const [open, setOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [plantillas, setPlantillas] = useState<AlertaPlantillaDefecto[]>([])
  const [plantillasLoaded, setPlantillasLoaded] = useState(false)
  const router = useRouter()
  const supabase = createClient()

  // Fetch active templates when dialog opens
  useEffect(() => {
    if (!open || plantillasLoaded) return
    supabase
      .from('alerta_plantillas_defecto')
      .select('*')
      .eq('activa', true)
      .order('orden')
      .then(({ data }) => {
        setPlantillas(data || [])
        setPlantillasLoaded(true)
      })
  }, [open, plantillasLoaded])

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      nombre: '',
      fecha_inicio: '',
      hora_inicio: '18:00',
      hora_fin: '21:00',
      whatsapp_link: '',
    },
  })

  const fechaInicio = form.watch('fecha_inicio')
  const claseDates = useMemo(() => generateClassDates(fechaInicio), [fechaInicio])
  const dayName = useMemo(() => getDayName(fechaInicio), [fechaInicio])

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setSubmitting(true)
    try {
      const dates = generateClassDates(values.fecha_inicio)
      const fechaFin = dates[dates.length - 1]
      const dia = getDayName(values.fecha_inicio)

      // 1. Insert curso (clase_dates + clases_completadas auto-generated by DB trigger)
      const { data: curso, error: cursoError } = await supabase
        .from('cursos')
        .insert({
          nombre: values.nombre,
          fecha_inicio: values.fecha_inicio,
          fecha_fin: fechaFin,
          dias_cursado: dia,
          horarios: `${values.hora_inicio} - ${values.hora_fin}`,
          whatsapp_link: values.whatsapp_link,
        })
        .select('id, nombre')
        .single()

      if (cursoError) throw cursoError

      // 2. Auto-generate alerts from templates
      const alertasToInsert = plantillas.map(p => ({
        descripcion: p.descripcion_template.replace(/\{curso_nombre\}/g, values.nombre),
        fecha_vencimiento: computeAlertDate(p.anchor, p.offset_dias, dates),
        tipo: 'curso',
        referencia_id: curso.id,
        color_etiqueta: p.color_etiqueta,
        origen: 'plantilla_defecto',
      }))

      const { error: alertasError } = alertasToInsert.length > 0
        ? await supabase.from('alertas').insert(alertasToInsert)
        : { error: null }

      if (alertasError) {
        // Rollback: delete the curso if alertas fail
        await supabase.from('cursos').delete().eq('id', curso.id)
        throw alertasError
      }

      // 3. Auto-generate communication checklist linked to this curso
      const { error: checklistError } = await supabase
        .from('curso_comunicaciones_checklist')
        .insert([
          { curso_id: curso.id, tipo_mensaje: 'Bienvenida enviada' },
          { curso_id: curso.id, tipo_mensaje: 'Material enviado' },
          { curso_id: curso.id, tipo_mensaje: 'Aviso modelo Clase 2' },
          { curso_id: curso.id, tipo_mensaje: 'Aviso evaluacion Clase 5' },
          { curso_id: curso.id, tipo_mensaje: 'Promo talleres enviada' },
        ])

      if (checklistError) {
        // Rollback: delete alertas + curso if checklist fails
        await supabase.from('alertas').delete().eq('referencia_id', curso.id)
        await supabase.from('cursos').delete().eq('id', curso.id)
        throw checklistError
      }

      toast.success('Curso creado con 5 clases automaticas', {
        description: `${curso.nombre} - ${dia}s de ${values.hora_inicio} a ${values.hora_fin}.`,
      })

      form.reset()
      setOpen(false)
      if (onSuccess) onSuccess()
      router.refresh()
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err)
      toast.error('Error al crear el curso.', { description: message })
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger render={<Button className="bg-primary text-primary-foreground hover:bg-primary/90 font-semibold h-9 text-xs shadow-lg shadow-primary/15" />}>
        <PlusCircle className="w-3.5 h-3.5 mr-1.5" />
        Nuevo Curso
      </DialogTrigger>
      <DialogContent className="sm:max-w-[540px] glass border-border/50">
        <DialogHeader>
          <DialogTitle className="text-lg">Nuevo Curso</DialogTitle>
          <DialogDescription className="text-xs">
            Selecciona la fecha de inicio y el sistema genera automaticamente 5 clases semanales consecutivas.
          </DialogDescription>
        </DialogHeader>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 pt-1">
            <FormField
              control={form.control}
              name="nombre"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="text-xs font-medium">Nombre del Curso</FormLabel>
                  <FormControl>
                    <Input placeholder="Ej: Barberia Inicial - Marzo" className="bg-input/30 h-10 text-sm" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="fecha_inicio"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="text-xs font-medium">Fecha de Inicio (Clase 1)</FormLabel>
                  <FormControl>
                    <Input type="date" className="bg-input/30 h-10 text-sm block w-full" {...field} />
                  </FormControl>
                  <FormDescription className="text-[11px]">
                    Se generan 5 clases consecutivas el mismo dia de la semana.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />

            {/* Auto-generated preview */}
            {fechaInicio && claseDates.length > 0 && (
              <div className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4 text-primary" />
                    <span className="text-xs font-semibold text-primary">
                      {dayName}s - {NUM_CLASES} clases
                    </span>
                  </div>
                </div>
                <div className="grid grid-cols-5 gap-1.5">
                  {claseDates.map((d, i) => (
                    <div key={d} className="text-center px-2 py-2 rounded-lg bg-card/80 border border-border/30">
                      <p className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">Clase {i + 1}</p>
                      <p className="text-xs font-semibold mt-0.5 tabular-nums">
                        {format(new Date(d + 'T12:00:00'), 'dd/MM', { locale: es })}
                      </p>
                    </div>
                  ))}
                </div>
                {plantillas.length > 0 && (
                  <div className="space-y-1.5 pt-1">
                    <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground font-semibold uppercase tracking-wider">
                      <Bell className="w-3 h-3" />
                      <span>{plantillas.length} alertas automaticas</span>
                    </div>
                    {plantillas.map(p => (
                      <div key={p.id} className="flex items-center gap-2 text-[10px]">
                        <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${
                          p.color_etiqueta === 'naranja' ? 'bg-naranja' : p.color_etiqueta === 'rojo' ? 'bg-rojo' : 'bg-azul'
                        }`} />
                        <span className="text-muted-foreground truncate">
                          {p.descripcion_template.replace(/\{curso_nombre\}/g, '...')}
                        </span>
                        <span className="text-muted-foreground/50 shrink-0">
                          {ANCHOR_LABELS[p.anchor] || p.anchor}{p.offset_dias !== 0 ? ` ${p.offset_dias > 0 ? '+' : ''}${p.offset_dias}d` : ''}
                        </span>
                      </div>
                    ))}
                  </div>
                )}
                {plantillas.length === 0 && plantillasLoaded && (
                  <div className="flex items-start gap-1.5 text-[10px] text-muted-foreground">
                    <Info className="w-3 h-3 shrink-0 mt-0.5" />
                    <span>No hay plantillas de alertas configuradas. Configuralas en Alertas &gt; Plantillas.</span>
                  </div>
                )}
              </div>
            )}

            <div className="grid grid-cols-2 gap-3">
              <FormField
                control={form.control}
                name="hora_inicio"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-xs font-medium">Hora Inicio</FormLabel>
                    <FormControl>
                      <Input type="time" className="bg-input/30 h-10 text-sm block w-full cursor-pointer" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="hora_fin"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-xs font-medium">Hora Fin</FormLabel>
                    <FormControl>
                      <Input type="time" className="bg-input/30 h-10 text-sm block w-full cursor-pointer" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            <FormField
              control={form.control}
              name="whatsapp_link"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="text-xs font-medium">Link Grupo de WhatsApp</FormLabel>
                  <FormControl>
                    <Input placeholder="https://chat.whatsapp.com/..." className="bg-input/30 h-10 text-sm" {...field} />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <div className="pt-3">
              <Button type="submit" disabled={submitting} className="w-full h-10 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold text-sm shadow-lg shadow-primary/15">
                {submitting ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
                Crear Curso ({NUM_CLASES} clases)
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  )
}
